# Generated by Django 6.0.6 on 2026-06-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "verbose_name": "Ürün Niteliği",
                "verbose_name_plural": "Ürün Nitelikleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productattributevalue",
            options={
                "verbose_name": "Ürün Nitelik Değeri",
                "verbose_name_plural": "Ürün Nitelik Değerleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productspecification",
            options={"ordering": ["sort_order"], "verbose_name": "Ürün Nitelik Değeri"},
        ),
        migrations.AlterModelOptions(
            name="productspecificationgroup",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Ürün Özellik Grubu",
                "verbose_name_plural": "Ürün Özellik Grupları",
            },
        ),
    ]
