# Generated by Django 6.0.6 on 2026-06-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productattribute_producttag_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürün",
            },
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "verbose_name": "Ürün Özelliği",
                "verbose_name_plural": "Ürün Özellikleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productattributevalue",
            options={
                "verbose_name": "Ürün Özellik Değeri",
                "verbose_name_plural": "Ürün Özellik Değerleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Ürün Görseli",
                "verbose_name_plural": "Ürün Görselleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ürün İncelemesi",
                "verbose_name_plural": "Ürün İncelemeleri",
            },
        ),
        migrations.AlterModelOptions(
            name="producttag",
            options={
                "verbose_name": "Ürün Etiketi",
                "verbose_name_plural": "Ürün Etiketleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "verbose_name": "Ürün Varyantı",
                "verbose_name_plural": "Ürün Varyantları",
            },
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="values",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="barcode",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="compare_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productimage",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariantValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productattribute",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productattributevalue",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_values",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Varyant Değeri",
                "verbose_name_plural": "Ürün Varyant Değerleri",
            },
        ),
    ]
