# Generated by Django 6.0.6 on 2026-06-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Sipariş", "verbose_name_plural": "Sipariş"},
        ),
        migrations.AlterModelOptions(
            name="orderaddress",
            options={
                "verbose_name": "Sipariş Adresi",
                "verbose_name_plural": "Sipariş Adresi",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Sipariş Ürünü",
                "verbose_name_plural": "Sipariş Ürünleri",
            },
        ),
        migrations.AlterModelOptions(
            name="ordernote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sipariş Notu",
                "verbose_name_plural": "Sipariş Notları",
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatushistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sipariş Durum Geçmişi",
                "verbose_name_plural": "Sipariş Durum Geçmişi",
            },
        ),
    ]
