# Generated by Django 6.0.6 on 2026-06-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Kategoriler",
                "verbose_name_plural": "Kategori",
            },
        ),
    ]
