# Generated by Django 6.0.6 on 2026-06-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Sepet", "verbose_name_plural": "Sepet"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Sepet Ürünü",
                "verbose_name_plural": "Sepet Ürünleri",
            },
        ),
    ]
