# Generated by Django 6.0.6 on 2026-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Marka",
                "verbose_name_plural": "Marka",
                "ordering": ["name"],
            },
        ),
    ]
