# Generated by Django 6.0.6 on 2026-06-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "Markalar",
                "verbose_name_plural": "Marka",
            },
        ),
    ]
