# Generated by Django 6.0.6 on 2026-06-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_alter_brand_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "Marka",
                "verbose_name_plural": "Marka",
            },
        ),
    ]
