# Generated by Django 6.0.6 on 2026-06-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "Kupon", "verbose_name_plural": "Kupon"},
        ),
    ]
