# Generated by Django 6.0.6 on 2026-06-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingcompany",
            options={
                "verbose_name": "Kargo Firması",
                "verbose_name_plural": "Kargo Firması",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={
                "verbose_name": "Kargo Yöntemi",
                "verbose_name_plural": "Kargo Yöntemi",
            },
        ),
    ]
