# Generated by Django 6.0.6 on 2026-06-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ürün Yorumu",
                "verbose_name_plural": "Ürün Yorumları",
            },
        ),
    ]
