# Generated by Django 6.0.6 on 2026-06-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "verbose_name": "İstek Listesi",
                "verbose_name_plural": "İstek Listesi",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlistitem",
            options={
                "verbose_name": "İstek Listesi Ürünü",
                "verbose_name_plural": "İstek Listesi Ürünleri",
            },
        ),
    ]
